name: Testing

on:
  workflow_run:
    workflows: ["Run Bandit"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest

      # Add more steps for additional testing if needed
